const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";

const NEW_MESSAGE_ALEART = "NEW_MESSAGE_ALEART";

const NEW_REQUEST = "NEW_REQUEST";

export {
    ALERT,
    REFETCH_CHATS,
    NEW_ATTACHMENT,
    NEW_MESSAGE_ALEART,
    NEW_REQUEST,
};
